spring.application.name=fraud-ml-client
server.port=8080

# URL of the Python FastAPI ML service
ml.service.url=http://localhost:8000

# Logging
logging.level.com.example=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=GET,POST
