package com.example.springai.controller;

import com.example.springai.model.FraudAlert;
import com.example.springai.model.FraudExplanation;
import com.example.springai.service.FraudExplainerService;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/fraud")
public class FraudExplainerController {

    private final FraudExplainerService explainerService;

    public FraudExplainerController(FraudExplainerService explainerService) {
        this.explainerService = explainerService;
    }

    @GetMapping("/health")
    public java.util.Map<String, String> health() {
        return java.util.Map.of("status", "UP", "service", "spring-ai-fraud-explainer");
    }

    /**
     * POST /api/fraud/explain
     *
     * Accepts a FraudAlert (ML model output) and returns a structured
     * FraudExplanation generated by the LLM via Spring AI.
     *
     * Example request body:
     * {
     *   "transactionId": "TXN-8821",
     *   "accountId": "ACC-1042",
     *   "amount": 1850.00,
     *   "currency": "USD",
     *   "fraudProbability": 0.92,
     *   "riskLevel": "HIGH",
     *   "hourOfDay": 3,
     *   "merchantRiskScore": 0.80,
     *   "velocity30d": 22,
     *   "geoRiskScore": 0.75,
     *   "merchantCategory": "FUEL",
     *   "cardPresent": false
     * }
     */
    @PostMapping("/explain")
    public FraudExplanation explain(@RequestBody FraudAlert alert) {
        return explainerService.explain(alert);
    }

    /**
     * POST /api/fraud/ask
     *
     * Free-text Q&A endpoint — ask any fraud-analysis question.
     * Useful for analysts investigating a pattern.
     *
     * Example body: "Why is a 3 AM FUEL purchase with card-not-present high risk?"
     */
    @PostMapping("/ask")
    public String ask(@RequestBody String question) {
        return explainerService.ask(question);
    }
}
